joia_kernel/config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  delete "catalog_wine_varieties/:id" => "catalogs#destroy_wine_variety"
  post   "add_new_wine_variety" => "catalogs#add_new_wine_variety"

  root 'main#index'

  resources :news
  resources :news_attachments
  resources :categories
  resources :countries
  resources :regions
  resources :manufacturers
  resources :colors
  resources :wine_varieties
  resources :catalogs
  resources :types
  resources :catalog_wine_varieties
  resources :users
  resources :sessions
  resources :imports
  resources :export_tos

  # get "/:idd" => "main#index"

end

joia_kernel/app/models/catalog.rb
# encoding: UTF-8
class Catalog < ActiveRecord::Base
  has_attached_file :avatar

  belongs_to :price
  belongs_to :catalog_wine_variety

  has_many :manufacturer
  has_many :category
  has_many :color

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each  do |catalog|
        csv << catalog.attributes.values_at(*column_names)
      end
    end
  end
end

joia_kernel/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :catalog
end

joia_kernel/app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :catalog
end

joia_kernel/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :region, dependent: :destroy
  belongs_to :manufacturer
end

joia_kernel/app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  belongs_to :catalog

  has_many :country
  has_many :region
end

joia_kernel/app/models/news.rb
class News < ActiveRecord::Base
  has_many :news_attachments, dependent: :destroy
end

joia_kernel/app/models/news_attachment.rb
class NewsAttachment < ActiveRecord::Base
  belongs_to :news
  has_attached_file :att_file
end

joia_kernel/app/models/price.rb
class Price < ActiveRecord::Base
  has_many :catalog
  has_many :type
end

joia_kernel/app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :country
  belongs_to :manufacturer
end

joia_kernel/app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :price
  belongs_to :user
end

joia_kernel/app/models/user.rb
class User < ActiveRecord::Base
  has_many :type
  has_secure_password
  validates_presence_of :email
  validates_uniqueness_of :email
end

joia_kernel/app/models/wine_variety.rb
class WineVariety < ActiveRecord::Base
  belongs_to :catalog_wine_variety
end

joia_kernel/app/helpers/colors_helper.rb
module ColorsHelper
end

joia_kernel/app/helpers/imports_helper.rb
module ImportsHelper
end

joia_kernel/app/helpers/main_helper.rb
module MainHelper
end

joia_kernel/app/helpers/news_helper.rb
module NewsHelper
end

joia_kernel/app/helpers/prices_helper.rb
module PricesHelper
end

joia_kernel/app/helpers/regions_helper.rb
module RegionsHelper
end

joia_kernel/app/helpers/types_helper.rb
module TypesHelper
end

joia_kernel/app/helpers/users_helper.rb
module UsersHelper
end

joia_kernel/app/views/layouts/_menu.html.erb
<ul id="nav">
  <li>
    <% if current_user %>
      <%= link_to current_user.email + ": Log out", "logout" %>
    <% else %>
      <%= link_to "Log in", "login" %>
    <% end %>
  </li>
  <li><a href="" onclick="return false;">Настройки</a>
    <ul>

      <hr>
      <li><%= link_to "Каталог", catalogs_path %></li>
      <hr>
      <li><%= link_to "Экспорт", export_tos_path %></li>
      <hr>
      <li><%= link_to "Типы", types_path %></li>
      <li><%= link_to "Страны / регионы", countries_path %></li>
      <li><%= link_to "Цвета", colors_path %></li>
      <li><%= link_to "Категории", categories_path %></li>
      <li><%= link_to "Сорта вин", wine_varieties_path %></li>
      <li><%= link_to "Производители", manufacturers_path %></li>
      <hr>
      <li><%= link_to "Новости", news_index_path %></li>
      <hr>
      <li><%= link_to "Пользователи", users_path %></li>
      <hr>
      <li><%= link_to "Закачка справочника", imports_path %></li>
      <hr>

    </ul>
  </li>
</ul>

joia_kernel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>