joia_kernel/config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  delete "catalog_wine_varieties/:id" => "catalogs#destroy_wine_variety"
  post   "add_new_wine_variety" => "catalogs#add_new_wine_variety"

  root 'main#index'

  resources :news
  resources :news_attachments
  resources :categories
  resources :countries
  resources :regions
  resources :manufacturers
  resources :colors
  resources :wine_varieties
  resources :catalogs
  resources :types
  resources :catalog_wine_varieties
  resources :users
  resources :sessions
  resources :imports
  resources :export_tos

  # get "/:idd" => "main#index"

end

joia_kernel/app/models/catalog.rb
# encoding: UTF-8
class Catalog < ActiveRecord::Base
  has_attached_file :avatar

  belongs_to :price
  belongs_to :catalog_wine_variety

  has_many :manufacturer
  has_many :category
  has_many :color

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each  do |catalog|
        csv << catalog.attributes.values_at(*column_names)
      end
    end
  end
end

joia_kernel/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :catalog
end

joia_kernel/app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :catalog
end

joia_kernel/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :region, dependent: :destroy
  belongs_to :manufacturer
end

joia_kernel/app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  belongs_to :catalog

  has_many :country
  has_many :region
end

joia_kernel/app/models/news.rb
class News < ActiveRecord::Base
  has_many :news_attachments, dependent: :destroy
end

joia_kernel/app/models/news_attachment.rb
class NewsAttachment < ActiveRecord::Base
  belongs_to :news
  has_attached_file :att_file
end

joia_kernel/app/models/price.rb
class Price < ActiveRecord::Base
  has_many :catalog
  has_many :type
end

joia_kernel/app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :country
  belongs_to :manufacturer
end

joia_kernel/app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :price
  belongs_to :user
end

joia_kernel/app/models/user.rb
class User < ActiveRecord::Base
  has_many :type
  has_secure_password
  validates_presence_of :email
  validates_uniqueness_of :email
end

joia_kernel/app/models/wine_variety.rb
class WineVariety < ActiveRecord::Base
  belongs_to :catalog_wine_variety
end

joia_kernel/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :check_admin
  def index
    @countries = Country.all
    @new_country = Country.new
  end
  def create
    Country.create(name: params[:country][:name])
    redirect_to(countries_path)
  end
  def destroy
    Country.find(params[:id]).destroy
    redirect_to(countries_path)
  end
  def show
    @country_id = params[:id]
    @regions = Region.where('country_id = ?', params[:id])
    @new_region = Region.new
  end
end

joia_kernel/app/helpers/catalogs_helper.rb
module CatalogsHelper
  def init
    @manufacturers = Manufacturer.all
    @categories = Category.all
    @colors = Color.all
    @types = Type.all
    @wine_variety = WineVariety.all
  end
  def init_wine_varieties
    @wine_variety = WineVariety.all
  end
end

joia_kernel/app/helpers/colors_helper.rb
module ColorsHelper
end

joia_kernel/app/helpers/countries_helper.rb
module CountriesHelper
end

joia_kernel/app/helpers/imports_helper.rb
module ImportsHelper
end

joia_kernel/app/helpers/main_helper.rb
module MainHelper
end

joia_kernel/app/helpers/news_helper.rb
module NewsHelper
end

joia_kernel/app/helpers/prices_helper.rb
module PricesHelper
end

joia_kernel/app/helpers/regions_helper.rb
module RegionsHelper
end

joia_kernel/app/helpers/types_helper.rb
module TypesHelper
end

joia_kernel/app/helpers/users_helper.rb
module UsersHelper
end

joia_kernel/app/views/countries/index.html.erb
<br><br>
<div>
  <div class="countries" style="float:left;width:50%;">

    <%= form_for @new_country do |f| %>
      <%= f.label :"Новая страна " %> <%= f.text_field :name, style: "width: 60%;" %><%= f.submit value: "Сохранить" %>
    <% end %>

    <table>
      <tr>
        <th>
          Наименование
        </th>
        <th>
        </th>
      </tr>
      <% @countries.each do |c| %>
        <tr>
          <td>
            <%= link_to c.name, country_path(c), remote: true %>
          </td>
          <td>
            <a data-confirm="Вы действительно хотите удалить страну?" data-method="delete" href="/countries/<%= c.id %>" rel="nofollow">
              <img src="/assets/del.png"></a>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="regions" style="float:left;width:50%;">

  </div>
</div>

joia_kernel/app/views/countries/show.js.erb
$('.regions').html("<%= escape_javascript render 'regions/index' %>");