joia_kernel/config/routes.rb
Rails.application.routes.draw do

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  delete "catalog_wine_varieties/:id" => "catalogs#destroy_wine_variety"
  post   "add_new_wine_variety" => "catalogs#add_new_wine_variety"

  root 'main#index'

  resources :news
  resources :news_attachments
  resources :categories
  resources :countries
  resources :regions
  resources :manufacturers
  resources :colors
  resources :wine_varieties
  resources :catalogs
  resources :types
  resources :catalog_wine_varieties
  resources :users
  resources :sessions
  resources :imports
  resources :export_tos

  # get "/:idd" => "main#index"

end

joia_kernel/app/models/catalog.rb
# encoding: UTF-8
class Catalog < ActiveRecord::Base
  has_attached_file :avatar

  belongs_to :price
  belongs_to :catalog_wine_variety

  has_many :manufacturer
  has_many :category
  has_many :color

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each  do |catalog|
        csv << catalog.attributes.values_at(*column_names)
      end
    end
  end
end

joia_kernel/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :catalog
end

joia_kernel/app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :catalog
end

joia_kernel/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :region, dependent: :destroy
  belongs_to :manufacturer
end

joia_kernel/app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  belongs_to :catalog

  has_many :country
  has_many :region
end

joia_kernel/app/models/news.rb
class News < ActiveRecord::Base
  has_many :news_attachments, dependent: :destroy
end

joia_kernel/app/models/news_attachment.rb
class NewsAttachment < ActiveRecord::Base
  belongs_to :news
  has_attached_file :att_file
end

joia_kernel/app/models/price.rb
class Price < ActiveRecord::Base
  has_many :catalog
  has_many :type
end

joia_kernel/app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :country
  belongs_to :manufacturer
end

joia_kernel/app/models/type.rb
class Type < ActiveRecord::Base
  belongs_to :price
  belongs_to :user
end

joia_kernel/app/models/user.rb
class User < ActiveRecord::Base
  has_many :type
  has_secure_password
  validates_presence_of :email
  validates_uniqueness_of :email
end

joia_kernel/app/models/wine_variety.rb
class WineVariety < ActiveRecord::Base
  belongs_to :catalog_wine_variety
end

joia_kernel/app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  before_filter :check_admin
  def index
    @catalogs = Catalog.all
  end
  def new
    @catalog = Catalog.new
  end
  def show
    @catalog = Catalog.find(params[:id])
    @prices = Price.where('catalog_id = ?', params[:id])
    @catalog_w_v = CatalogWineVariety.where('catalog_id = ?', params[:id])
  end
  def create
    catalog = Catalog.create(catalogs_params)
    save_price(catalog.id, params[:price], params[:discount])
    save_wine_varieties(catalog.id, params[:variety])
    redirect_to(catalogs_path)
  end
  def update
    Catalog.find(params[:id]).update(catalogs_params)
    save_price(params[:id], params[:price], params[:discount])
    save_wine_varieties(params[:id], params[:variety])
    redirect_to(catalogs_path)
  end
  def destroy
    Catalog.find(params[:id]).destroy
    Price.where('catalog_id = ?', params[:id]).destroy_all
    redirect_to(catalogs_path)
  end
  def destroy_wine_variety
    id = CatalogWineVariety.find(params[:id]).catalog_id
    CatalogWineVariety.find(params[:id]).destroy
    @catalog_w_v = CatalogWineVariety.where('catalog_id = ?', id)
  end
  def add_new_wine_variety
    CatalogWineVariety.create(percent: params[:new][:percent],
                              catalog_id: params[:new][:catalog_id],
                              wine_variety_id: params[:new][:wine_variety_id])
    @catalog_w_v = CatalogWineVariety.where('catalog_id = ?', params[:new][:catalog_id])
  end
  private
  def catalogs_params
    params.require(:catalog).permit( :name,
                                     :name_original,
                                     :description,
                                     :abv,
                                     :volume,
                                     :amount,
                                     :honors,
                                     :barcode,
                                     :avatar,

                                     :manufacturer_id,
                                     :category_id,
                                     :color_id )
  end
  def save_price(id, price, discount)
    Price.where('catalog_id = ?', id.to_i).destroy_all
    Type.all.each do |type|
      Price.create(catalog_id: id, type_id: type.id, price: price[type.id.to_s].to_i, discount: discount[type.id.to_s].to_i)
    end
  end
  def save_wine_varieties(id, variety)
    CatalogWineVariety.where('catalog_id = ?', id.to_i).destroy_all
    unless variety.nil?
      variety.each_key do |v|
        CatalogWineVariety.create(wine_variety_id: v.to_i, catalog_id: id.to_i, percent: variety[v].to_i) unless variety[v].to_i == 0
      end
    end
  end
end

joia_kernel/app/helpers/catalogs_helper.rb
module CatalogsHelper
  def init
    @manufacturers = Manufacturer.all
    @categories = Category.all
    @colors = Color.all
    @types = Type.all
    @wine_variety = WineVariety.all
  end
  def init_wine_varieties
    @wine_variety = WineVariety.all
  end
end

joia_kernel/app/helpers/colors_helper.rb
module ColorsHelper
end

joia_kernel/app/helpers/imports_helper.rb
module ImportsHelper
end

joia_kernel/app/helpers/main_helper.rb
module MainHelper
end

joia_kernel/app/helpers/news_helper.rb
module NewsHelper
end

joia_kernel/app/helpers/prices_helper.rb
module PricesHelper
end

joia_kernel/app/helpers/regions_helper.rb
module RegionsHelper
end

joia_kernel/app/helpers/sessions_helper.rb
module SessionsHelper
end

joia_kernel/app/helpers/types_helper.rb
module TypesHelper
end

joia_kernel/app/helpers/users_helper.rb
module UsersHelper
end

joia_kernel/app/views/catalogs/_form.html.erb
<% init %>

<form name="input" action="/add_new_wine_variety" method="post" data-remote="true">
  <%= hidden_field_tag "new[catalog_id]", @catalog.id %>
  <%= c.label :"Добавить винный сорт: " %><%= select_tag "new[wine_variety_id]", options_from_collection_for_select(@wine_variety, :id, :name) %>
  <%= text_field_tag "new[percent]", 0 %>
  <input type="submit" value="Добавить">
</form>
<%= form_for @catalog do |c| %>
  <!--Задаем сортовой состав-->
  <div class="catalog_wine_varieties">
    <%= render 'catalogs/index_wine_variety' %>
  </div>

  <!--Задание цены и скидки-->
  <% @types.each do |type| %>
    <% if action_name == "new" %>
      <%= c.label "Цена для "+type.name+" : " %>
      <%= text_field_tag "price["+type.id.to_s+"]", 0 %>
      <%= c.label "Скидка: " %>
      <%= text_field_tag "discount["+type.id.to_s+"]", 0 %>
    <% else %>
      <% price_each = @prices.where('type_id = ?', type).first %>
      <%= c.label "Цена для "+type.name+" : " %>
      <%= text_field_tag "price["+type.id.to_s+"]", price_each.price %>
      <%= c.label "Скидка: " %>
      <%= text_field_tag "discount["+type.id.to_s+"]", price_each.discount %>
    <% end %>
  <% end %>
  <%= c.label :"Наименование " %><%= c.text_field :name %>
  <%= c.label :"Наименование оригинальное " %><%= c.text_field :name_original %>
  <%= c.label :"Описание " %><%= c.text_area :description %>
  <%= c.label :"Крепость " %><%= c.text_field :abv %>
  <%= c.label :"Объем " %><%= c.text_field :volume %>
  <%= c.label :"Бутылок в упаковке " %><%= c.text_field :amount %>
  <%= c.label :"Награды " %><%= c.text_field :honors %>
  <%= c.label :"Штрих-код " %><%= c.text_field :barcode %>
  <%= c.label :"Фото " %><%= c.file_field :avatar %>
  <%= c.label :"Производитель " %><%= c.select :manufacturer_id, options_from_collection_for_select(@manufacturers, :id, :name, @catalog.manufacturer_id), include_blank: true %>
  <%= c.label :"Категория " %><%= c.select :category_id, options_from_collection_for_select(@categories, :id, :name, @catalog.category_id), include_blank: true %>
  <%= c.label :"Цвет " %><%= c.select :color_id, options_from_collection_for_select(@colors, :id, :name, @catalog.color_id), include_blank: true %>
  <%= c.submit value: "Сохранить" %>
<% end %>

joia_kernel/app/views/catalogs/_index_wine_variety.html.erb
<% init_wine_varieties %>

<% if action_name == "new" %>
  <% @wine_variety.each do |w_v| %>
    <%= label_tag "Процент винного сорта - "+w_v.name+" : " %>
    <%= text_field_tag "variety["+w_v.id.to_s+"]", 0 %>
    <br>
  <% end %>
<% else %>
  <% @catalog_w_v.each do |cwv| %>
    <%= label_tag "Процент винного сорта - "+@wine_variety.find(cwv.wine_variety_id).name+" : " %>
    <%= text_field_tag "variety["+cwv.wine_variety_id.to_s+"]", cwv.percent.to_s %>
    <a data-confirm="Вы действительно хотите удалить вино?" data-remote="true" data-method="delete" href="/catalog_wine_varieties/<%= cwv.id %>" rel="nofollow">
      <img src="/assets/del.png"></a>
    <br>
  <% end %>
<% end %>

joia_kernel/app/views/catalogs/add_new_wine_variety.js.erb
$('.catalog_wine_varieties').html("<%= escape_javascript render 'catalogs/index_wine_variety' %>");

joia_kernel/app/views/catalogs/destroy_wine_variety.js.erb
$('.catalog_wine_varieties').html("<%= escape_javascript render 'catalogs/index_wine_variety' %>");

joia_kernel/app/views/catalogs/index.html.erb
<div>
  <div class="catalogs" style="float:left;width:50%;">

    <%= link_to "Добавить вино", new_catalog_path, remote: true %>

    <table>
      <tr>
        <th>
          Наименование
        </th>
        <th>
        </th>
      </tr>
      <% @catalogs.each do |c| %>
        <tr>
          <td>
            <%= link_to c.name, catalog_path(c), remote: true %>
          </td>
          <td>
            <a data-confirm="Вы действительно хотите удалить вино?" data-method="delete" href="/catalogs/<%= c.id %>" rel="nofollow">
              <img src="/assets/del.png"></a>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="catalog" style="float:left;width:50%;">

  </div>
</div>

joia_kernel/app/views/catalogs/new.js.erb
$('.catalog').html("<%= escape_javascript render 'catalogs/form' %>");

joia_kernel/app/views/catalogs/show.js.erb
$('.catalog').html("<%= escape_javascript render 'catalogs/form' %>");